# settings:
#   legacy:
#     force: false
#     interval: 0s
# schema:
# - name: winzinternal
#   path: .
#   commands:
#     build:
#       method: go build -o winzinternal.o
#       status: true
#     run:
#       method: "./winzinternal.o"
#       status: true
#   watcher:
#     scripts:
#     - type: before
#       command: pkill server-api
#       output: true
#     extensions:
#     - go
#     paths:
#     - /
#     ignored_paths:
#     - .git
#     - .realize
#     - vendor
settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: trying
  path: .
  commands:
    install:
      status: true
      method: go build -o tmp/trying.o main.go
    run:
      status: true
      method: tmp/trying.o
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor